### ISSUE TITLE
Update to 1.3 - Port OSM nominatim geocoder.

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/geocoder#1]
Mostly : 
- Cache results
- Better handling of countries

Some code cleanup

OpenStreetMap nominatim geocoder tested with addressfield.

Remaining tasks
- Geocode from virtual fields/entity property instead of just real fields : depends on a full featured port of Entity API.
- Port remaining handlers - TODO

**Comment by jenlampton** [comment]
PR merged, closing this issue.
