### ISSUE TITLE
Typo in other module URLs in README.md

### ISSUE THREAD

**Issue by quinnanya** [backdrop-contrib/geocoder#17]
It looks like the URLs for Addressfield and Geofield in README.md (and, correspondingly, the Backdrop project page and installer text) have typos: https://github.com/nbackdrop-contrib/addressfield and https://github.com/nbackdrop-contrib/geofield. Changing **n**backdrop-contrib to backdrop-contrib works fine for Addressfield, but it looks like there isn't an official release for Geofield yet.

**Comment by jenlampton** [comment]
Thank you, fixed!
