### ISSUE TITLE
Remove dependency on geophp

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/geocoder#18]
It seems that `geophp` is included in `geofield` -- we should remove the dependency on `geophp` and set it up for `geofield`. I'm doing some testing now.

--
PR: https://github.com/backdrop-contrib/geocoder/pull/19

**Comment by laryn** [comment]
We have a WFM here: https://github.com/backdrop-contrib/geocoder/commit/bd8211cae642ec218daae5b4921be8d1cc6be22b#commitcomment-37549127

**Comment by jenlampton** [comment]
I've merged the PR, so I think this can be closed?
