### ISSUE TITLE
Remove gifad from Maintainers?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/geocoder#22]
@klonos writes on Zulip:

>  the user gifad no longer exists on GitHub. For security reasons perhaps remove them from the list of maintainers (someone may claim that username and potentially do harm if they request to be added)? ...we could add their name in the "Credits" section, and link to https://www.drupal.org/u/gifad instead.

**Comment by jenlampton** [comment]
I just pushed a commit for this.
