### ISSUE TITLE
Geophp dependency

### ISSUE THREAD

**Issue by PepeMty** [backdrop-contrib/geocoder#25]
Hey, guys.
I just downloaded the geocoder module and can't install it because it appears to depend on the geophp module.
Browsing the issues I found that there is a commit son August 2020, which doesn't shows among the releases...

Hope some admin / maintainer can fix this.

Thanks!

**Comment by jenlampton** [comment]
GeoPHP is now included in geofield, so as long as you are running geofield you shouldn't need anything else. I'm going to issue a new release, and hopefully it will be a lot clearer in the updated version of the module.

**Comment by PepeMty** [comment]
Thanks, Jen...!
Sorry for the tardy reply.
