### ISSUE TITLE
Update OSM nominatim plugin to latest API and fix urlencoding

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/geocoder#26]
This code is old: https://github.com/backdrop-contrib/geocoder/blob/1.x-1.x/plugins/geocoder_handler/openstreetmap_nominatim.inc#L23

And it's not really up to date with the actual API:
https://nominatim.org/release-docs/latest/api/Search/

But most of all, it contains a bug re urlencoding of parameters, which prevents query strings with non-ASCII chars to return a result.

Suggested fixes:

```
function geocoder_openstreetmap_nominatim($address, $options = array()) {
  $api_url = 'https://nominatim.openstreetmap.org/search';

  $params = array(
    'q' => $address,
    'format' => 'json',
    'limit' => 1,
  );
  $request = backdrop_http_request($api_url . '?' . backdrop_http_build_query($params));
  $data = json_decode($request->data);
  return _geocoder_openstreetmap_nominatim_geometry($data);
}
```
1. Uses the proper api url, uses https
2. Fixes param urlencoding

Is there any interest in a pull request?

**Comment by herbdool** [comment]
@indigoxela if someone creates a PR the @backdrop-contrib/bug-squad can review, test and merge (after a waiting period for the maintainer).

**Comment by indigoxela** [comment]
Here we go, a [PR](https://github.com/backdrop-contrib/geocoder/pull/27) is available for testing and review.

**Comment by olafgrabienski** [comment]
Thanks for the PR! I've applied it to a test site, and it fixes the URL encoding issue for me: Without the PR I was not able to filter a view (by proximity) for a city with an umlaut in it's name, the view just displayed all results. With the PR the filter for German cities like "Lübeck" or "München" works like a charm.

**Comment by herbdool** [comment]
I looked at the code and it looks good to me. @jenlampton would you like to merge this PR to fix the bug? Otherwise, let me know and I can merge it and create a bug fix release. Or, if I hear nothing for a couple weeks, I'll do so. Anyone, feel free to remind me if I forget.

**Comment by argiepiano** [comment]
Merging on behalf of the @backdrop-contrib/bug-squad
