### ISSUE TITLE
geocoder_google_field() not defined when using geocoder() with google handler

### ISSUE THREAD

**Issue by juanolalla** [backdrop-contrib/geocoder#3]
I've tried to use Geocoder API with this code for a specific address:

```php
$point = geocoder('google',$address);
```
And it throws an error when tried to execute the field_callback:
**Fatal error: Call to undefined function geocoder_google_field() in geocoder.module on line 58**

It looks like the handler plugin files are not loaded so the callback doesn't exist.

Also the Geocoder admin settings at /admin/config/content/geocoder doesn't work. I've looked and it is not using Config Management, using the Drupal system_settings_form() which doesn't work in Backdrop, instead of returning a specific form.

It looks like this port is not complete yet?

**Comment by juanolalla** [comment]
I've solved this from the current Drupal 7 Geocoder branch, porting the module. Here is the repository https://github.com/juanolalla/geocoder.

I had started another repo because I didn't realize that there was an existing project porting Geocoder to Backdrop (I had looked in https://backdropcms.org/modules thinking that was the same as searching in https://github.com/backdrop-contrib. However the good thing is that my port has the lastest changes and I've solved the problem of loading the files without ctools in a pretty simple way.

I've also changed the variable_get() and variable_set() functions to use Config Management instead. And I have made the module work without drupal compatibility, replacing all uses of drupal, Drupal and DRUPAL through the code.

I'm not sure if should create a big pull request over this project, or just replace it with the updated port in another way.

**Comment by juanolalla** [comment]
Here is the pull request with the complete port solving all these problems https://github.com/backdrop-contrib/geocoder/pull/4

**Comment by jenlampton** [comment]
Thanks for the PR @juanolalla!  You may have noticed this already, but `system_settings_form()` does still work in more recent versions of Backdrop. If you want that form to save into a single config file, all you need to do is add a `$form['#config'] = 'whatever.settings';` for the form, and voila!

**Comment by juanolalla** [comment]
Thanks @jenlampton, I didn't know that, I think it is a great help. Although in this case it's just about creating the submit button manually or not, because the submit callback function was customized anyway. I'll take that into account from now on for a more straightforward way of porting future modules.

**Comment by jenlampton** [comment]
PR merged, thanks @juanolalla for all your help with geocoder!
