### ISSUE TITLE
Geofield is not being populated with geocode (using Google API)

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/geocoder#9]
I have the Geofield, Geocoder, GeoPHP modules installed and things seem to be working for me except for the automatic population of the Geofield from the address field. 

I have a key set up with Google and am getting this error:
Exception: Google API returned bad status.\nStatus: REQUEST_DENIED in geocoder_google() (line 124 of ..../htdocs/modules/geocoder/plugins/geocoder_handler/google.inc).

- I have tried changing the 'Application Restrictions' on my API Key. 
- I have tried changing the settings for 'Use HTTPS ?' on the Geofield itself

Some issues that MIGHT be related:

Geofield remains empty when I choose "Geocode from another field"
https://www.drupal.org/project/geocoder/issues/3002517

Google API returned bad status
https://www.drupal.org/project/geocoder/issues/2789803

**Comment by jenlampton** [comment]
I'm usin pthe Geofield, Geocoder, GeoPHP modules on several of my sites, and I'm not having any trouble with the first delta of geofields being populated with data geocoded from address fields. However, for the second delta and onward, no geodata is returned. 

See https://github.com/backdrop-contrib/geocoder/issues/10 for more on that issue.

**Comment by stpaultim** [comment]
Sorry, I forgot to update this issue. I was able to use the module with Bing API - so, the problem is apparently related to my Google API key and/or how I've configured the module. I posted some additional comments here: https://forum.backdropcms.org/forum/adding-multiple-addressesnodes-map-using-views

**Comment by sbgraphicdesign** [comment]
I've just had the exact same issue myself as @stpaultim with Google Maps.

It appears that you need to have a billing account with Google and linked to to the project as well. You get a credit limit so, at least for smaller websites, you'll likely still not to pay for using Google Maps and Geocoding in your site.

**Comment by jenlampton** [comment]
Sounds like the readme needs to be updated. Maybe the installation or requirements section needs an update!

**Comment by jenlampton** [comment]
See https://github.com/backdrop-contrib/geocoder/issues/16

**Comment by mazzech** [comment]
Hi @stpaultim, where did you find the Geophp module? I can't get Geocoder to work without it...?!

**Comment by laryn** [comment]
I'm also having trouble getting a Google API key to work and have (temporarily) activated a Bing key, which seems to be working for now. I'd love to get that solved, though -- @sbgraphicdesign do you have the Google key working?

**Comment by jenlampton** [comment]
@laryn  if/when you figure out the Google maps API key issue, can you help me update the documentation in https://github.com/backdrop-contrib/geocoder/issues/16?

**Comment by laryn** [comment]
@jenlampton Will do. I'll likely be looking into that next week.

**Comment by stpaultim** [comment]
I was setting this up tonight to create a mapping blog post and ran into this problem again. 

Initially, I used BING for the geocodes, because I always get a headache when dealing with the GoogleMaps API interface. I got the geocodes working with BING. 

But then I realized that the Geofield Map modules only seems to support maps with Google API. So, forced to deal with the Google Maps API, I spent an hour getting the maps to display properly. Now that the maps are displaying properly and the Google API key seems to be working, why not use it for Geocoding as well. 

However, when I switched to using the GoogleMaps API for Geocoding, it broke again. In short, I'm unable to get this module working for GeoCoding and will probably revert to using BING again. 

`Exception: Google API returned bad status.\nStatus: REQUEST_DENIED in geocoder_google() (line 124 of /var/www/triplo/maps/simplo/src/modules/contrib/geocoder/plugins/geocoder_handler/google.inc).`

**Comment by mazzech** [comment]
Thank you Tim... here's my type of message in the console...

![Screenshot 2021-02-14 at 12 06 47](https://user-images.githubusercontent.com/5985692/107874935-5b072000-6ebd-11eb-8256-bc284c5d6e37.png)

**Comment by mazzech** [comment]
How do you even switch to bing coding? I create a Bing code, enter it here /admin/config/content/geocoder but can't switch to Bing mode anywhere...?

**Comment by stpaultim** [comment]
@mazzech - Do you have a "geofield" field on your content type? 

My content type is called "Locations" and it has the following two fields:

1) Address (addressfield module)
2) Geofield (geofield module)

The geofield field does not show up on the node form, it is populated by the geofield/geocoder modules with the lat and long. You can create a view to see if the geofield has any values. 

In the settings for the geofield you can select a Geocoder:

![geocoder](https://user-images.githubusercontent.com/3144571/107887110-5183b500-6ec9-11eb-825b-d4e3ca0080d2.png)

This is where I am unable to get Google GeoCoder to work. Let me know if you have success.

**Comment by stpaultim** [comment]
I'm going to close this issue. I'm using GeoCoder on another site with Google API and not having this problem.
